update . added if statement

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -39,7 +39,11 @@ jobs:
     - name: Set FUNCTION_APP_NAME_RECEIVE_LOG
       id: set_receive_log
       run: |
-        FUNCTION_APP_NAME_RECEIVE_LOG=$(terraform output -raw function_app_name_receive_log | grep -E '^[a-zA-Z0-9-]+$')
+        FUNCTION_APP_NAME_RECEIVE_LOG=$(terraform output -raw function_app_name_receive_log)
+        if [[ -z "$FUNCTION_APP_NAME_RECEIVE_LOG" ]]; then
+          echo "Error: FUNCTION_APP_NAME_RECEIVE_LOG is empty"
+          exit 1
+        fi
         echo "FUNCTION_APP_NAME_RECEIVE_LOG=$FUNCTION_APP_NAME_RECEIVE_LOG" >> $GITHUB_ENV
       working-directory: ./terraform
     
@@ -52,7 +56,11 @@ jobs:
     - name: Set FUNCTION_APP_NAME_RETRIEVE_LOG
       id: set_retrieve_log
       run: |
-        FUNCTION_APP_NAME_RETRIEVE_LOG=$(terraform output -raw function_app_name_retrieve_log | grep -E '^[a-zA-Z0-9-]+$')
+        FUNCTION_APP_NAME_RETRIEVE_LOG=$(terraform output -raw function_app_name_retrieve_log)
+        if [[ -z "$FUNCTION_APP_NAME_RETRIEVE_LOG" ]]; then
+          echo "Error: FUNCTION_APP_NAME_RETRIEVE_LOG is empty"
+          exit 1
+        fi
         echo "FUNCTION_APP_NAME_RETRIEVE_LOG=$FUNCTION_APP_NAME_RETRIEVE_LOG" >> $GITHUB_ENV
       working-directory: ./terraform
     
